"""Preamble (title/banner) lines before the header must be skipped, not eaten.

NASA's GISTEMP export opens with ``Land-Ocean: Global Means`` before the real
header; reading that caption as the header collapses the table to one column.
"""

import polars as pl

from auto_cleaner import CleanConfig
from auto_cleaner.ingest import read_any
from auto_cleaner.ingest.detect import detect_preamble, profile_source

GISTEMP_STYLE = (
    "Land-Ocean: Global Means\n"
    "Year,Jan,Feb,Mar\n"
    "1880,-.19,-.25,-.10\n"
    "1881,-.10,-.17,***\n"
    "1882,-.05,-.09,-.02\n"
)


def test_detect_preamble_counts_title_lines():
    assert detect_preamble(GISTEMP_STYLE, ",") == 1
    assert detect_preamble("Year,Jan\n1880,-.19\n1881,-.10\n", ",") == 0


def test_read_any_skips_preamble_and_keeps_real_header(tmp_path):
    src = tmp_path / "gistemp.csv"
    src.write_text(GISTEMP_STYLE)
    profile = profile_source(src)
    assert profile.skip_rows == 1 and profile.has_header

    df, report = read_any(src, CleanConfig(verbose=False))
    assert df.columns == ["Year", "Jan", "Feb", "Mar"]
    assert df.height == 3
    assert report.metrics["csv_preamble_lines"] == 1
    # The GISTEMP '***' missing marker must land as a real null.
    assert df.get_column("Mar").null_count() == 1


def test_ordinary_csv_is_untouched(tmp_path):
    src = tmp_path / "plain.csv"
    src.write_text("a,b\n1,x\n2,y\n3,z\n")
    df, report = read_any(src, CleanConfig(verbose=False))
    assert df.columns == ["a", "b"]
    assert df.height == 3
    assert "csv_preamble_lines" not in report.metrics


def test_multiline_banner_is_skipped(tmp_path):
    src = tmp_path / "export.csv"
    src.write_text(
        "Quarterly export - internal use\nGenerated by WarehouseTool\n"
        "id,amount,region\n1,10.5,eu\n2,11.0,us\n3,9.8,eu\n"
    )
    df, _ = read_any(src, CleanConfig(verbose=False))
    assert df.columns == ["id", "amount", "region"]
    assert df.height == 3


def test_streaming_path_respects_preamble(tmp_path):
    src = tmp_path / "gistemp.csv"
    src.write_text(GISTEMP_STYLE)
    cfg = CleanConfig(verbose=False).with_overrides(streaming=True)
    df, _ = read_any(src, cfg)
    assert df.columns == ["Year", "Jan", "Feb", "Mar"]
    assert isinstance(df, pl.DataFrame) and df.height == 3
